### ISSUE TITLE
Copyright violation

### ISSUE THREAD

**Issue by Poussinou** [js-labs/WalkieTalkie#20]
Hi @js-labs 

I found [this app](https://play.google.com/store/apps/details?id=ro.cjc5.pttdroid) on the Google Play Store. This guy just took your source code, added some ads in it and put it on the Store, without warning this is free software...

As you are the owner of the source code, feel free to open a request to google [here](https://support.google.com/legal/contact/lr_dmca?product=googleplay) to remove the false app from the Store, if it's your wish ;)

Don't forget to tell Google that:

* The app is licensed under GNU AGPL license and this guy is violating it;
* He is falsely claiming he made the app;
* Provide a link to this repo and some screenshot of your own app.

**Comment by js-labs** [comment]
Hi!
Thank you for information.
I'v seen few clones of my app on GooglePlay and claimed as a copyright violation.
But new clone apps appear all the time, seems it is time to check them again.

**Comment by Poussinou** [comment]
As you can see on my github account, I'm currently tracking the fake developers around the Google Play Store. Can you copy past the URLs of the clones here please, so that I can track them?

**Comment by Poussinou** [comment]
Hi @js-labs I found another one [here](https://play.google.com/store/apps/details?id=com.skyking.walkietalkie.policeradio) !

**Comment by js-labs** [comment]
Hi! Thank you for information.

**Comment by Poussinou** [comment]
All copycats here are down.

I'm closing this Issue, but please report it here in the future if you find other copycats.
