### ISSUE TITLE
Build err in android studio.

### ISSUE THREAD

**Issue by juni0604** [js-labs/WalkieTalkie#29]
Dear js-labs.

I tried to build this nice app but build error occured in android studio.

D:\WalkieTalkie-master (1)\WalkieTalkie-master\src\main\java\org\jsl\wfwt\ChannelSession.java
Error:(63, 53) error: cannot find symbol class Task

Error:(82, 29) error: constructor RetainableByteBufferCache in class RetainableByteBufferCache cannot be applied to given types;
required: boolean,int,int
found: boolean,int,ByteOrder,int
reason: actual and formal argument lists differ in length

D:\WalkieTalkie-master (1)\WalkieTalkie-master\src\main\java\org\jsl\wfwt\AudioRecorder.java
Error:(44, 53) error: cannot find symbol class Task

D:\WalkieTalkie-master (1)\WalkieTalkie-master\src\main\java\org\jsl\wfwt\HandshakeClientSession.java
Error:(44, 53) error: cannot find symbol class Task

Is the current source buildable in Android Studio? 
If possible, please let me know how.

Thanks.
Regards.

**Comment by js-labs** [comment]
Hi! Thank you for your report.
I made some changes in the js-collider framework API, and also changes in WalkieTalkie app to use the new API properly, but new js-collider version is not published yet. So, you have a few options for now:
1) build a WalkieTalkie app with recent source code of js-collilder framework
2) rollback few commits in WalkieTalkie app to build it properly with js-collider 0.1.2
3) wait few days, i am going to publish new js-collider framework and fix build failure of the WalkieTalkie app.

**Comment by juni0604** [comment]
Thanks you for your quick answer. 

I'll wait your fix.(option 3) 

Thanks. 
Regards.

**Comment by js-labs** [comment]
Problem with build is fixed.
