### ISSUE TITLE
Force Java7 when using Java7 functionality.

### ISSUE THREAD

**Issue by krt16s** [js-labs/WalkieTalkie#4]
When using features like the diamon operator, you should explicitly state the java version. you can do that by adding the following lines to `build.gradle` in the android section:

````
compileOptions {
    sourceCompatibility JavaVersion.VERSION_1_7
    targetCompatibility JavaVersion.VERSION_1_7
}
````

**Comment by js-labs** [comment]
Thank you, fixed.
