### ISSUE TITLE
Include a Changelog Link, within the F-Droid App', on Info' Page; 1.6.

### ISSUE THREAD

**Issue by locutis-of-borg-1999** [js-labs/WalkieTalkie#6]
Include a Changelog Link, within the F-Droid App', on Info' Page.  Not present, as of: 1.6.

**Comment by js-labs** [comment]
Hi, thank you for information.
Will do it with next release.

**Comment by locutis-of-borg-1999** [comment]
Do you, now, mean 1.8, because I see the info' page for 1.7, and it's not there.

https://f-droid.org/manual/html_node/Changelog.html#Changelog

**IF** it existed, you could use: https://github.com/js-labs/WalkieTalkie/releases  .

I've even seen some dev's use **THIS** type content (nonexistent for your project.):  https://raw.githubusercontent.com/js-labs/WalkieTalkie/HEAD/CHANGELOG.md

**Comment by js-labs** [comment]
Yes, will do it with 1.8
I published 1.8 on Play Market, will do it on F-Droid as well soon.

**Comment by locutis-of-borg-1999** [comment]
B-)  8-)

**Comment by js-labs** [comment]
ChangeLog added.
