### ISSUE TITLE
Feature: background watcher?

### ISSUE THREAD

**Issue by xenithorb** [js-labs/WalkieTalkie#7]
Feature request for a way to allow the app to background itself in such a way that app can still receive broadcasts?

Perhaps include a "wake up" packet at the beginning of a transmission in order to fully wake up device in order to be able to play the broadcast. (a la some kind of modern magic packet?)

Feature goals:

1. Allow app to be a service
2. Has the effect that after feature implementation, user can install app, turn screen off and let device go to sleep, can still receive broadcast audio. Perhaps preempt transmission is required to fully wake device?

**Comment by js-labs** [comment]
Hi!
Thank you for  the interest in the application.
I have many ideas how can improve it, and I thought about something like this as well, probably will be nice. But unfortunately I have no too much time to spend on this, can not promise it will be available soon.

**Comment by js-labs** [comment]
Feature is done, new version available on Google Play.

**Comment by tejohnso** [comment]
This doesn't seem to be working. I'm using version 1.11 from F-Droid.  After a few moments with the screen off, the device disappears from the list of available devices to contact.

I see you mentioned the new version is available on Play but F-Droid and Play show the same version (1.11) so I wouldn't expect different behaviour. Have they diverged in some way?

**Comment by js-labs** [comment]
Hi!Thank you for feedback.Sometimes android disable a service to reduce power consumtion.Could you share the device name and fiemware version you use?24 нояб. 2021 г. 17:25 пользователь Tyler Johnson ***@***.***> написал:
This doesn't seem to be working. I'm using version 1.11 from F-Droid.  After a few moments with the screen off, the device disappears from the list of available devices to contact.
I see you mentioned the new version is available on Play but F-Droid and Play show the same version (1.11) so I wouldn't expect different behaviour. Have they diverged in some way?

**Comment by tejohnso** [comment]
Both devices are GalaxyJ7Prime model SM-J727T1 with firmware. I don't see firmware version listed but Android version is 7.0 and build number is NRD90M.J727T1UVS3ARE1 if that helps.  

Also, I can confirm that the app is listed in the list of Running Services.
